vich_uploader:
    db_driver: orm
    metadata:
      type: attribute 
    mappings: 
      galeries:
        uri_prefix: /uploads/galeries
        upload_destination: "%kernel.project_dir%/public/uploads/galeries"
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer